// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbXep-wtOFD0QLDZeQxpo-VKR_A9laK8E',
    appId: '1:1003468608193:web:c21c0af81d92bd07027a40',
    messagingSenderId: '1003468608193',
    projectId: 'run-test-446f4',
    authDomain: 'run-test-446f4.firebaseapp.com',
    storageBucket: 'run-test-446f4.firebasestorage.app',
    measurementId: 'G-085E1KD8YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA77SdErIr1uD1Ws0peMT30EsyEOVsAZao',
    appId: '1:1003468608193:android:a5124a95ac353c08027a40',
    messagingSenderId: '1003468608193',
    projectId: 'run-test-446f4',
    storageBucket: 'run-test-446f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTsvcnjTKjKmgIP1N5PMKqUWlnM2s8EB0',
    appId: '1:1003468608193:ios:000b145deba50499027a40',
    messagingSenderId: '1003468608193',
    projectId: 'run-test-446f4',
    storageBucket: 'run-test-446f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterRunTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTsvcnjTKjKmgIP1N5PMKqUWlnM2s8EB0',
    appId: '1:1003468608193:ios:000b145deba50499027a40',
    messagingSenderId: '1003468608193',
    projectId: 'run-test-446f4',
    storageBucket: 'run-test-446f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterRunTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbXep-wtOFD0QLDZeQxpo-VKR_A9laK8E',
    appId: '1:1003468608193:web:2d1c2526015e3226027a40',
    messagingSenderId: '1003468608193',
    projectId: 'run-test-446f4',
    authDomain: 'run-test-446f4.firebaseapp.com',
    storageBucket: 'run-test-446f4.firebasestorage.app',
    measurementId: 'G-J6WJKPZHG2',
  );
}
